/// Flutter icons Custom_dashboard
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_dashboard
///      fonts:
///       - asset: fonts/Custom_dashboard.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Custom_dashboard {
  Custom_dashboard._();

  static const _kFontFam = 'Dashboard';
  static const String? _kFontPkg = null;

  static const IconData dashboard =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
