/// Flutter icons Door
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Door
///      fonts:
///       - asset: fonts/Door.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Door {
  Door._();

  static const _kFontFam = 'Door';
  static const String? _kFontPkg = null;

  static const IconData open_door_fill = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
